export const demoItems = [
  {
    id: "demo-budget-guide-v1",
    name: "Demo: Agent budgeting guide",
    description: "A short guide to planning an agent's spending allowance.",
    preview: "Plan a budget, compare offers, and keep purchase receipts.",
    amount: "1000000",
    deliverable: "A plain-text budgeting guide",
    content: [
      "Agent budgeting guide — demonstration edition",
      "1. Define the task and the resources the agent may purchase.",
      "2. Set a total allowance and a maximum price per purchase.",
      "3. Compare the listing's scope and deliverable before buying.",
      "4. Reserve part of the allowance for follow-up purchases.",
      "5. Review delivered content and retain the payment receipt.",
      "Example: a 6-token allowance can cover this guide (1), the demo dataset (2), and the demo checklist (3).",
    ].join("\n\n"),
  },
  {
    id: "demo-spending-dataset-v1",
    name: "Demo: Sample spending dataset",
    description:
      "A downloadable CSV of synthetic agent purchases for analysis.",
    preview:
      "Five illustrative purchases with category, token cost, and outcome.",
    amount: "2000000",
    deliverable: "A CSV file containing five synthetic purchase records",
    filename: "demo-spending.csv",
    mediaType: "text/csv",
    content: [
      "id,category,cost_tokens,outcome,synthetic",
      "PUR-001,guide,1,delivered,true",
      "PUR-002,dataset,2,delivered,true",
      "PUR-003,checklist,3,delivered,true",
      "PUR-004,guide,1,delivered,true",
      "PUR-005,dataset,2,delivered,true",
      "",
    ].join("\n"),
  },
  {
    id: "demo-purchase-checklist-v1",
    name: "Demo: Purchase review checklist",
    description: "A reusable Markdown checklist for reviewing agent purchases.",
    preview: "Check scope, allowance, delivery, and receipts in one template.",
    amount: "3000000",
    deliverable: "A downloadable Markdown checklist",
    filename: "demo-purchase-checklist.md",
    mediaType: "text/markdown",
    content: [
      "# Purchase review checklist",
      "",
      "- [ ] Record the task and expected deliverable.",
      "- [ ] Check the seller, listing version, and quoted price.",
      "- [ ] Confirm the purchase fits the remaining allowance.",
      "- [ ] Complete payment and retain the transaction hash.",
      "- [ ] Open the delivered text or downloaded file.",
      "- [ ] Compare the result with the promised scope.",
      "- [ ] Record remaining allowance and any follow-up work.",
      "",
      "Demo template for the Agent Spend Guard walkthrough.",
    ].join("\n"),
  },
] as const
